name: greg_colours
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: https://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
