name: greg_colours
description: GRAG
version: 1.0.0
repository: https://github.com/TTFTCUTS/greg_colours
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: https://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
